
import { Account, AccountTier, AccountStatus } from './types';

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: '1',
    name: 'Zoom Video Communications Inc.',
    tier: AccountTier.TIER1,
    owner: 'Carlos',
    primaryContact: 'Lagos Project',
    keyContacts: 'Eric Yuan (CEO), Kelly Steckelberg (CFO)',
    email: 'contact@zoom.com',
    location: 'Global',
    annualRevenue: 8807991,
    engagementFocus: 'Relationship breadth, in-person QBRs',
    qbrFrequency: 'Quarterly',
    lastQbrDate: '2025-11-15',
    nextQbrDate: '2026-02-01',
    status: AccountStatus.ACTIVE,
    notes: 'In person.. Dinner preferable Jasper: Lagos project active ($100k MRR)',
    qbrCompletion: { q1: false, q2: false, q3: false, q4: false }
  },
  {
    id: '2',
    name: 'Nvidia Corporation',
    tier: AccountTier.TIER1,
    owner: 'Wade',
    primaryContact: 'Wade\'s Contact',
    keyContacts: 'Jensen Huang (CEO), Colette Kress (CFO)',
    email: 'info@nvidia.com',
    location: 'Global',
    annualRevenue: 3288080,
    engagementFocus: 'Relationship breadth, in-person QBRs',
    qbrFrequency: 'Quarterly',
    lastQbrDate: '2025-11-20',
    nextQbrDate: '2026-02-04',
    status: AccountStatus.ACTIVE,
    notes: 'Strategic hardware alignment',
    qbrCompletion: { q1: false, q2: false, q3: false, q4: false }
  },
  {
    id: '3',
    name: 'Cisco - Jasper',
    tier: AccountTier.TIER1,
    owner: 'Josh L.',
    primaryContact: 'Mike Hayes',
    keyContacts: 'Chuck Robbins, Maria Martinez (COO)',
    email: 'mhayes@cisco.com',
    location: 'NoCal',
    annualRevenue: 3210445,
    engagementFocus: 'Relationship breadth, in-person QBRs',
    qbrFrequency: 'Quarterly',
    lastQbrDate: '2025-11-10',
    nextQbrDate: '2026-02-07',
    status: AccountStatus.ACTIVE,
    notes: 'Project active; Umbrella/Webex integration',
    qbrCompletion: { q1: false, q2: false, q3: false, q4: false }
  },
  {
    id: '4',
    name: 'Zscaler',
    tier: AccountTier.TIER1,
    owner: 'Carlos',
    primaryContact: 'Security Lead',
    keyContacts: 'Jay Chaudhry (CEO), Remo Canessa (CFO)',
    email: 'ops@zscaler.com',
    location: 'Global',
    annualRevenue: 3074574,
    engagementFocus: 'Relationship breadth, in-person QBRs',
    qbrFrequency: 'Quarterly',
    lastQbrDate: '2025-12-05',
    nextQbrDate: '2026-02-10',
    status: AccountStatus.ACTIVE,
    notes: 'High velocity growth account',
    qbrCompletion: { q1: false, q2: false, q3: false, q4: false }
  },
  {
    id: '5',
    name: 'McAfee',
    tier: AccountTier.TIER1,
    owner: 'Eric',
    primaryContact: 'Security Team',
    keyContacts: 'Greg Johnson (CEO), Peter Leav (Board)',
    email: 'it@mcafee.com',
    location: 'Global',
    annualRevenue: 1317051,
    engagementFocus: 'Relationship breadth, in-person QBRs',
    qbrFrequency: 'Quarterly',
    lastQbrDate: '2025-12-01',
    nextQbrDate: '2026-02-13',
    status: AccountStatus.ACTIVE,
    notes: 'Stable legacy transition',
    qbrCompletion: { q1: false, q2: false, q3: false, q4: false }
  },
  {
    id: '6',
    name: 'Proofpoint',
    tier: AccountTier.TIER2,
    owner: 'Josh L.',
    primaryContact: 'Brian Adams',
    keyContacts: 'Sumit Dhawan (CEO)',
    email: 'badams@proofpoint.com',
    location: 'NoCal',
    annualRevenue: 396549,
    engagementFocus: 'Operational scaling, product alignment',
    qbrFrequency: 'Quarterly',
    lastQbrDate: '2025-12-10',
    nextQbrDate: '2026-03-06',
    status: AccountStatus.ACTIVE,
    notes: 'Scaling quickly, technical audit required',
    qbrCompletion: { q1: false, q2: false, q3: false, q4: false }
  },
  {
    id: '7',
    name: 'Mullvad',
    tier: AccountTier.TIER3,
    owner: 'Wade',
    primaryContact: 'Privacy Lead',
    keyContacts: 'Jan Jonsson (CEO)',
    email: 'ops@mullvad.net',
    location: 'Vegas',
    annualRevenue: 450717,
    engagementFocus: 'Root-cause analysis, stabilization',
    qbrFrequency: 'Semi-Annual',
    lastQbrDate: '2025-10-15',
    nextQbrDate: '2026-03-30',
    status: AccountStatus.AT_RISK,
    notes: 'Monitoring for revenue erosion',
    qbrCompletion: { q1: false, q2: false, q3: false, q4: false }
  }
];
