"""
Core data models for the agentic sales intelligence platform.
"""

from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime
from enum import Enum
import uuid


class Priority(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class InsightStatus(str, Enum):
    UNREAD = "unread"
    READ = "read"
    ACTIONED = "actioned"
    DISMISSED = "dismissed"


class AgentInstanceStatus(str, Enum):
    ACTIVE = "active"
    PAUSED = "paused"
    ERROR = "error"
    RUNNING = "running"


PRIORITY_RANK = {
    Priority.CRITICAL: 0,
    Priority.HIGH: 1,
    Priority.MEDIUM: 2,
    Priority.LOW: 3,
    Priority.INFO: 4,
}


@dataclass
class SourceObject:
    """A click-to-source reference back to the original data source."""
    source_type: str
    object_type: str
    object_id: str
    display_name: str
    deep_link: str
    snippet: str = ""
    retrieved_at: str = ""

    def to_dict(self) -> dict:
        return {
            "source_type": self.source_type,
            "object_type": self.object_type,
            "object_id": self.object_id,
            "display_name": self.display_name,
            "deep_link": self.deep_link,
            "snippet": self.snippet,
            "retrieved_at": self.retrieved_at,
        }


@dataclass
class ConnectorResult:
    """Result from an integration connector query."""
    connector_name: str
    intent: str
    records: list[dict] = field(default_factory=list)
    sources: list[SourceObject] = field(default_factory=list)
    raw_text: str = ""
    record_count: int = 0
    error: str = ""


@dataclass
class AgentContext:
    """Context passed to an agent when it runs."""
    account_ids: list[str] = field(default_factory=list)
    account_names: list[str] = field(default_factory=list)
    config: dict = field(default_factory=dict)
    time_range_days: int = 90
    user_message: str = ""
    must_win_accounts: list[str] = field(default_factory=list)
    instance_id: str = ""


@dataclass
class InsightCard:
    """An insight generated by an agent, shown in the intelligence feed."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    agent_instance_id: str = ""
    agent_blueprint_id: str = ""
    account_id: str = ""
    account_name: str = ""
    priority: Priority = Priority.INFO
    title: str = ""
    summary: str = ""
    detail: dict = field(default_factory=dict)
    sources: list[SourceObject] = field(default_factory=list)
    actions: list[dict] = field(default_factory=list)
    status: InsightStatus = InsightStatus.UNREAD
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    expires_at: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "agent_instance_id": self.agent_instance_id,
            "agent_blueprint_id": self.agent_blueprint_id,
            "account_id": self.account_id,
            "account_name": self.account_name,
            "priority": self.priority.value if isinstance(self.priority, Priority) else self.priority,
            "title": self.title,
            "summary": self.summary,
            "detail": self.detail,
            "sources": [s.to_dict() for s in self.sources],
            "actions": self.actions,
            "status": self.status.value if isinstance(self.status, InsightStatus) else self.status,
            "created_at": self.created_at,
            "expires_at": self.expires_at,
        }


@dataclass
class AgentResult:
    """Result of running an agent."""
    success: bool
    insights: list[InsightCard] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)
